# Generated by Django 4.2.5 on 2023-09-24 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestaocarteira', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=124)),
                ('objetivo', models.CharField(max_length=356)),
                ('tipo_tarefa', models.CharField(choices=[('QBR', 'QBR'), ('EBR', 'EBR'), ('K', 'Kickoff'), ('R', 'Reunião'), ('L', 'Ligação'), ('V', 'Visita'), ('W', 'Whatsapp'), ('O', 'Outros')], max_length=3)),
                ('status_tarefa', models.CharField(choices=[('AG', 'Agendada'), ('AT', 'Atrasada'), ('FN', 'Finalizada'), ('NR', 'Não realizada')], max_length=3)),
                ('atribuido_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuido_a', to='usuarios.usuario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaocarteira.cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criado_por', to='usuarios.usuario')),
            ],
        ),
    ]
