# Generated by Django 4.2.5 on 2023-10-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='data_da_tarefa',
        ),
        migrations.AddField(
            model_name='negocio',
            name='status_do_negocio',
            field=models.CharField(choices=[('O', 'Oportunidade'), ('C', 'Contato feito'), ('N', 'Em negociação'), ('F', 'Fechado')], default='O', max_length=1),
        ),
    ]
