# Generated by Django 4.2.5 on 2023-10-05 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('gestaocarteira', '0003_contrato_data_final'),
        ('negocios', '0002_remove_negocio_data_da_tarefa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestaocarteira.cliente'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='valor_estimado',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
