# Generated by Django 4.2.5 on 2023-10-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_negocio_cliente_negocio_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
