# Generated by Django 4.2.5 on 2023-10-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaocarteira', '0002_alter_carteira_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
