# Generated by Django 4.2.5 on 2023-09-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('funcao', models.CharField(choices=[('CSM', 'CSM'), ('ADM', 'Administração')], max_length=3)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('data_login', models.DateField()),
            ],
        ),
    ]
