# Generated by Django 4.2.5 on 2023-10-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_data_login_remove_usuario_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
