# Generated by Django 4.2.5 on 2023-10-04 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestaocarteira', '0002_alter_carteira_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Churn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_churn', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaocarteira.cliente')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaocarteira.contrato')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
